# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Metrics

on:
  schedule: 
    - cron: 0 0 1 * *
  workflow_dispatch:
  
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS }}
          
          config_timezone: Asia/Seoul
          config_twemoji: yes
          
          plugin_isocalendar: yes
          plugin_languages: yes
          plugin_habits: yes
          plugin_followup: yes
